### ISSUE TITLE
About third-party models using diffusers pipeline

### ISSUE THREAD

**Issue by klossm** [seruva19/kubin#102]
I have found other people's trained fine-tuning models decoder_fp16.ckpt and prior_fp16.ckpt elsewhere. Is there a corresponding tool that can be converted into a model that can be used by Diffusers?

**Comment by seruva19** [comment]
There is an "official" script https://github.com/huggingface/diffusers/blob/main/scripts/convert_kandinsky_to_diffusers.py
It is not added into GUI yet, but I am planning to do it.

**Comment by klossm** [comment]
Thank you. I'll try.
