### ISSUE TITLE
Problem with mixing images

### ISSUE THREAD

**Issue by seruva19** [seruva19/kubin#105]

**Comment by xyzzart** [comment]
something wrong with that update. what with oversaturated colors? mixing results are crap( i love the old one version more

**Comment by user425846** [comment]
Yup, old version is so much better than 2.2. i dont know what they did here

xyzzart ***@***.***> schrieb am Do. 13. Juli 2023 um 22:35:

**Comment by seruva19** [comment]
@xyzzart It is possible that I confused some params in 'mix' section while rewriting methods for 2.2.
I'll check it tomorrow.

**Comment by Blucknote** [comment]
> @xyzzart It is possible that I confused some params in 'mix' section 

I guess it's not about repo and model itself. I did not tried mix in bot, but regular txt2pic cursed too

**Comment by seruva19** [comment]
@Blucknote I feel like prompts I got used to in 2.1 do not work at all.  It is closer to SD in terms of prompt understanding now. Anyway, might take some time to figure it out.

**Comment by seruva19** [comment]
@xyzzart  I suspect that a change of default prior steps from 5 to 25 might be the reason of why mixing images turns out bad (in web app). I changed it because number of prior steps is used in a different context in 2.2 than in 2.1 and it has to be higher that in 2.1. 
Try to set it to 5 and see what happens.
I will do some tests tomorrow, too.

**Comment by xyzzart** [comment]
> @xyzzart I suspect that a change of default prior steps from 5 to 25 might be the reason of why mixing images turns out bad (in web app). I changed it because number of prior steps is used in a different context in 2.2 than in 2.1 and it has to be higher that in 2.1. Try to set it to 5 and see what happens. I will do some tests tomorrow, too.

they just fixed color issue in a telegram bot. прием

**Comment by seruva19** [comment]
Mixing brings result different from 2.1, but overall works fine.
![image](https://github.com/seruva19/kubin/assets/26826215/493611d8-b244-4b09-bfff-ef797f11413b)

But it's "param-volatile" mode, adding negative prompts or changing image weights influences result a lot.

**Comment by xyzzart** [comment]
is it only me or its slowed generating after update? i use 2.1 model and it takes me 3 minutes to generate 1 image 960x960. as far as i remeber i was able to generate even bigger resolutions faster
