### ISSUE TITLE
problem to run 2.1 version 

### ISSUE THREAD

**Issue by xyzzart** [seruva19/kubin#106]
im gettin this kind of error when trying to run 2.1 (no diffusers) version. i want the older version back,how it was a while ago)
![image](https://github.com/seruva19/kubin/assets/87940617/9a032546-e2c9-4d6a-b644-c969ab783fdc)

**Comment by xyzzart** [comment]
bro,i dont get it,sorry) i dont know what to remove.just check for yourself that colab wont run with 2.1 model. can you fix that,please?

**Comment by seruva19** [comment]
No worries!
And I just fixed it - should run fine now. Haven't check "vanilla" 2.1 for a while )

**Comment by xyzzart** [comment]
> No worries! And I just fixed it - should run fine now. Haven't check "vanilla" 2.1 for a while )

Thnx for quick reply! Now it works! I have tried using 2.1 diffusers  -also something wrong with colors and exposition.well, they shoud fix that bug in a few days. by the way - side bar is pretty awesome 👍

**Comment by xyzzart** [comment]
oh noo..one more error((
![image](https://github.com/seruva19/kubin/assets/87940617/bc5d3046-2991-4e0f-b2c3-8d1bf0ffdc09)

**Comment by seruva19** [comment]
Sorry. That's my bad again. I should have tested old versions before deploying. I'll fix it in 10 mins.

**Comment by seruva19** [comment]
Should work now.

**Comment by xyzzart** [comment]
ill try it out now. ui restart button will be a nice feature

**Comment by seruva19** [comment]
Yes, this is planned. I need this button as well 😐

**Comment by xyzzart** [comment]
> Should work now.

it works now. but,you have changed something.the results are not the same they were earlier(( im using mixing mode,the first render took a lot of time.something was downloading..maybe its caused by the updates(

**Comment by xyzzart** [comment]
my bad,everything is ok. thanks again for your help
