### ISSUE TITLE
 CUDA is not available

### ISSUE THREAD

**Issue by tushengzhang** [seruva19/kubin#109]
D:\back\Kandinsky-2\kandinsky\kubin\venv\lib\site-packages\torch\amp\autocast_mode.py:204: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')

**Comment by seruva19** [comment]
It cannot locate your GPU perhaps?
Try to run `install-torch.bat` from app root.

**Comment by tushengzhang** [comment]
I tried, and it still doesn't work, but thank you very much.

**Comment by seruva19** [comment]
Sorry, can't really help here, as this seems to be unrelated with web-GUI.
If you have multiple GPUs, try changing 'device' parameter is settings. If it is 'cuda:0', change it to 'cuda' and vice-versa.
The same problem seems to be described [here](https://blog.csdn.net/weixin_44409833/article/details/127177563), maybe there is something useful mentioned?
As a last resort, I suggest reinstalling NVidia GPU drivers :)

**Comment by tushengzhang** [comment]
> 抱歉，这里帮不上什么忙，因为这似乎与 web-GUI 无关。 如果您有多个 GPU，请尝试更改“设备”参数设置。如果是“cuda:0”，请将其更改为“cuda”，反之亦然。[这里](https://blog.csdn.net/weixin_44409833/article/details/127177563) 似乎描述了同样的问题，也许提到了一些有用的东西？ 作为最后的手段，我建议重新安装 NVidia GPU 驱动程序:)[](https://blog.csdn.net/weixin_44409833/article/details/127177563)

thank you
