### ISSUE TITLE
Colab not working

### ISSUE THREAD

**Issue by xyzzart** [seruva19/kubin#112]
is it only me or its slowed generating after update? i use 2.1 model and it takes me 3 minutes to generate 1 image 960x960. as far as i remeber i was able to generate even bigger resolutions faster. im talking about mixing mode

**Comment by seruva19** [comment]
I don't think any of 2.1 inference methods changed, I only upgraded diffusers to include 2.2 support. If there will be more reports about slowdowns, I will do tests against multiple versions of the app.

**Comment by xyzzart** [comment]
> I don't think any of 2.1 inference methods changed, I only upgraded diffusers to include 2.2 support. If there will be more reports about slowdowns, I will do tests against multiple versions of the app.
i think nobody useses 2.1 model now) today im getting errors with higher resolution (1158x960)..and it just stop the colab
![image](https://github.com/seruva19/kubin/assets/87940617/ec716c52-2e0c-45f4-8864-c400f6d2edfe)

**Comment by seruva19** [comment]
That's strange, but, frankly speaking, I never tested 2.1 in colab with resolutions higher than 768x768. I will look into it in a few days, though I have no idea what can be the problem.

**Comment by xyzzart** [comment]
> That's strange, but, frankly speaking, I never tested 2.1 in colab with resolutions higher than 768x768. I will look into it in a few days, though I have no idea what can be the problem.

it was working a time ago...also it generated way faster than now. ok,maybe you can check that issue in near future/

**Comment by xyzzart** [comment]
> That's strange, but, frankly speaking, I never tested 2.1 in colab with resolutions higher than 768x768. I will look into it in a few days, though I have no idea what can be the problem.

(( sorry for being annoying but something wrong with 2.1 model. im getting error everytime now( even with low resolution.It was working some hours ago(

**Comment by xyzzart** [comment]
> 

any luck of fixing this issue?(

**Comment by seruva19** [comment]
I haven't yet figured out exact origin of the problem (namely, why RAM usage spikes on model initial launch so hard that it exceeds colab's 12.7 Gb). There was a recent update in Google cloud services, and this was one of the factors that led to error; another one is still high memory usage of the app itself.

Here is a temporary workaround that may help: start runtime, but then activate "Use fallback runtime version" in command palette. I was able to launch 2.1 vanilla model with that.

**Comment by xyzzart** [comment]
> I haven't yet figured out exact origin of the problem (namely, why RAM usage spikes on model initial launch so hard that it exceeds colab's 12.7 Gb). There was a recent update in Google cloud services, and this was one of the factors that led to error; another one is still high memory usage of the app itself.
> 
> Here is a temporary workaround that may help: start runtime, but then activate "Use fallback runtime version" in command palette. I was able to launch 2.1 vanilla model with that.

feeling awkward but when should i activate it? before i launch the cells? is that "использовать резервную версию среды выполнения" command?

**Comment by Blucknote** [comment]
Colab prohibits UIs, may be its case?
source: https://www.reddit.com/r/StableDiffusion/comments/12t8tc7/comment/jh2rwe1/?utm_source=share&utm_medium=web2x&context=3

**Comment by seruva19** [comment]
I don't think so, because trick  with switching to legacy environment succeeds.
Also 2.2 model works too (by relaunching the last cell after crash).
These errors did not happen until recent colab [environment upgrade to Ubuntu 22.04](https://github.com/googlecolab/colabtools/issues/3778). There seems to be a fix that might (I am actually not sure 🙂) cure it, it is described here: https://github.com/TheLastBen/fast-stable-diffusion/issues/2359, I will try to adapt it. 
Also I need to test against older versions of the app, it is possible I somehow made some mistake in code that increases RAM usage too much.

**Comment by seruva19** [comment]
I applied fix to colab proposed by [almfahd41](https://github.com/almfahd41) in #125.
After that I was able to generate vanilla 2.1 images without switching to legacy runtime, no RAM overflow.
