### ISSUE TITLE
Diffusers module，kandinsky 2.2  8G VRAM can't even run 256×256 images!

### ISSUE THREAD

**Issue by klossm** [seruva19/kubin#115]
8G vram to run 256×256 display vram is insufficient, using Kandinsky 2.2 diffusers module, also according to the wiki settings optimized, 2.1 can run 768×768

**Comment by seruva19** [comment]
That was the case with 2.1, new model requires more resources.
I will publish an update in monday, it will add some new optimizations.

**Comment by adrianpuiu** [comment]
Hi Sergey, long time no see man. How long dose it take to get the k2.2 working on local . i started the app but it took more than 160 seconds got bored and stopped it. now im trying second time

**Comment by seruva19** [comment]
@adrianpuiu Hi!
It takes a lot of time to download new models, maybe this is the reason?
