### ISSUE TITLE
clip-interrogator 0.6.0 breaking on Windows

### ISSUE THREAD

**Issue by mvlipka** [seruva19/kubin#119]
On Windows 11 using PowerShell, I am receiving:
`ModuleNotFoundError: No module named 'blip.models'` after running off `main`

It seems the PR last night that was merged, https://github.com/seruva19/kubin/pull/118, updates `clip-interrogator` to `0.6.0`

In order to run `./start.bat` I had to re-install `clip-interrogator` at version `0.5.0`

`pip install clip-interrogator==0.5.0`

kubin now works as expected after downgrading the package

**Comment by seruva19** [comment]
Thank you. I just commited and merged fix for this. It should work now without downgrading `clip-interrogator`.

**Comment by mvlipka** [comment]
Thanks for the swift response and action!
