### ISSUE TITLE
Allow manual download and use of model weights

### ISSUE THREAD

**Issue by Acephalia** [seruva19/kubin#128]
Hello, I have just reinstalled a fresh version of the GUI as my one was severely outdated. I keep getting stuck in a download loop where the script seems to terminate the model downloads for the safetensor files before they finish and then trying to redownload them from scratch. I've tried to wipe the models folder a couple of times and retry but no luck. 

Is there anyway I can download and place the files manually in the models folder? I noticed the auto download seems to create a lot of folders such as blobs, refs and snapshots. So I was a bit unsure of the paths to place the manually downloaded files in. Some assistance would be much appreciated. 

Thank you!

**Comment by seruva19** [comment]
Hello.
The whole downloading process is handled by the diffusers library, so there isn't much I can change here, but, yes, theoretically, you should be able to just clone repos with models from https://huggingface.co/kandinsky-community, put them into 'models' folder, and they will be fetched by the app, but I haven't tested it this way so cannot confirm the exact folder names and locations 🙂. If you can wait, I will test it tomorrow.

**Comment by Acephalia** [comment]
Hey thanks so much for the quick response. Of course more than happy to wait till you can check it. 

I did do some digging and it seems like manually downloading the files into the snapshots folder with the same folder hierarchy as the repo, and overwriting the existing symlinks seems to work. However it still seems to be pulling some models from the blobs folder so its using a bit of extra file space. I'm assuming this is where the symlinks are linked to. 

I guess if we could confirm whether placing cloned repos in the model folder does do the trick and what the correct folder name would be that would be great. No rush, whenever you can get to it is more than fine.

Thank you!

**Comment by seruva19** [comment]
This turns out to be not as easy as I thought it would be 🙂

Manually cloned pipelines are not recognized by the app; it still tries to freshly load them (and is attempting to use a different folder structure than in the original repo). Another thing to consider is that cloned repos are 3-4 times larger than the actual data required because all model variants are fetched – both PyTorch .bin files and SafeTensors. And, as far as I know, there is no reliable way to sparse clone specific files.

I will try to find a solution to this because sometimes it might be actually preferable to update weights manually instead of relying on automatic updates.

**Comment by Acephalia** [comment]
Jinx! I was literally writing an update with the same findings when you posted this haha. Deny detailed update is now trashed hahah. 

But yes, thank you for checking, no matter what I tried it seems to still want both files and it has to be in the snapshot folder with the numbered folder within.

Would certainly be nice to not have it take that much space but I can live with it. Thank you for your support!

**Comment by seruva19** [comment]
There must be some common way to solve it; I just haven't delved deep enough. But eventually, I'll figure this out :)

**Comment by Acephalia** [comment]
I’ll keep digging too. If you need a hand with anything just shout, anytime!
