### ISSUE TITLE
add min 1 value on sliders

### ISSUE THREAD

**Issue by adrianpuiu** [seruva19/kubin#13]
hey man,I hope you're well.

can you please  modify the sliders from:
  steps = gr.Slider(0 
  to 
  steps = gr.Slider(1 
for the image parameters and for the image **width** and **height** 
from 
width = gr.Slider(1, 1024, 768, step=1,
to 
width = gr.Slider(1, 1024, 768, step=**16**,
 or 
width = gr.Slider(1, 1024, 768, step=**32**,

**Comment by seruva19** [comment]
You're right, thank you. I will modify it ASAP.
I think the min width/height should also be set to at least 16.

**Comment by adrianpuiu** [comment]
also modify the from 1024 to 1280. will be easier to scale for 16:9 or 21:9 aspect ratios , lines 21, 22, 23 in t1i.py

      with gr.Row():
        width = gr.Slider(1, 1280, 768, step=1, label='Width')
        height = gr.Slider(1, 1280, 768, step=1, label='Height')

**Comment by seruva19** [comment]
Max dimension is set to 2048 in the commit https://github.com/seruva19/kubin/commit/c7bab119b68d507598d85f01098cd854b62d8e51.
It's on dev branch currently, I will merge into main shortly.
