### ISSUE TITLE
Mix mode getting error// (with 2.1 model)

### ISSUE THREAD

**Issue by xyzzart** [seruva19/kubin#154]
![image](https://github.com/seruva19/kubin/assets/87940617/f55071f5-042f-45e4-842b-ea1161856dc2)

**Comment by xyzzart** [comment]
aint working at all( in t2img mode also

**Comment by seruva19** [comment]
Google made an update to colab environment recently (https://colab.research.google.com/notebooks/relnotes.ipynb), so I had to do some changes as well.
Now it should work as expected.
