### ISSUE TITLE
please tell me the instructions for starting k3.

### ISSUE THREAD

**Issue by nikolaiusa** [seruva19/kubin#172]
I have a 64ram and two cards 3090 (24 GB) + 4090 (24GB)
I installed kubin and it works fine on k2.2

Can you write which version of K3 should I download and what settings should I make so that I could launch it?

**Comment by seruva19** [comment]
In 'Settings' tab, choose 'kd30' model and 'diffusers' pipeline. Apply settings and try to generate something. If it runs out of memory or runs too slow, try enabling sequential offloading (https://github.com/seruva19/kubin/wiki/Docs#kandinsky-3). I have 64 Gb RAM + RTX 3090, and cannot run diffusers-K3 without sequential offloading.

Another way is to switch to 'native' pipeline, which activates some optimizations by default and fits into 12 Gb VRAM.

**Comment by nikolaiusa** [comment]
I have an error cuda oom - maybe I need to enable some other options in the diffusers menu?


<img width="287" alt="2024-3-4 17-3-47" src="https://github.com/seruva19/kubin/assets/134322831/80141fb8-9744-47a2-9793-53a7cb02842d">
<img width="471" alt="2024-3-4 17-1-50" src="https://github.com/seruva19/kubin/assets/134322831/7e4202f7-498d-4d14-b9ba-f3400eca77b0">
<img width="481" alt="2024-3-4 17-1-38" src="https://github.com/seruva19/kubin/assets/134322831/5243c514-aec7-4773-a4d4-2a95e4f7dddb">
<img width="421" alt="2024-3-4 17-1-28" src="https://github.com/seruva19/kubin/assets/134322831/dd7f6ae2-dee7-44fa-bedb-3d272c1164db">

**Comment by nikolaiusa** [comment]
this version has been downloaded - https://huggingface.co/kandinsky-community/kandinsky-3

**Comment by nikolaiusa** [comment]
i turned on - Enable sequential CPU offload
and I have this speed at 4090 - 768x768
 32%|██████████████████████████▏                                                       | 16/50 [00:58<01:49,  3.23s/it]

**Comment by nikolaiusa** [comment]
Is this normal generation speed?

**Comment by seruva19** [comment]
With sequential offloading, yes, this is normal.
You can also try running a 'native' pipeline, it might be faster.

**Comment by nikolaiusa** [comment]
can I use multiple gpu?

**Comment by nikolaiusa** [comment]
> With sequential offloading, yes, this is normal. You can also try running a 'native' pipeline, it might be faster.

yes I tried it, the native one works faster.

To start generating, i need the Internet - tell me, is it possible to use it offline?


raceback (most recent call last):
  File "I:\ANACONDA3\envs\KANDINSKIY\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "I:\ANACONDA3\envs\KANDINSKIY\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "I:\ANACONDA3\envs\KANDINSKIY\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by nikolaiusa** [comment]
native  VS diffusers 
1min VS 3min 
for 1gen - 1280-1024 - 50step
on my ps

**Comment by seruva19** [comment]
> > With sequential offloading, yes, this is normal. You can also try running a 'native' pipeline, it might be faster.
> 
> yes I tried it, the native one works faster.
> 
> To start generating, i need the Internet - tell me, is it possible to use it offline? (probably to check versions or something like that)
> 
> raceback (most recent call last): File "I:\ANACONDA3\envs\KANDINSKIY\lib\site-packages\urllib3\connection.py", line 198, in _new_conn sock = connection.create_connection( File "I:\ANACONDA3\envs\KANDINSKIY\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "I:\ANACONDA3\envs\KANDINSKIY\lib\socket.py", line 955, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno 11001] getaddrinfo failed urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001DA595C3D00>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)

You need Internet on the first run to download all the models, but on subsequent runs it should work offline as well.

**Comment by nikolaiusa** [comment]
![20240305133842_A_kangaroo_holding_a_beer,](https://github.com/seruva19/kubin/assets/134322831/1ef34dee-fc0f-4e05-94b1-76c5935099cc)
thanks for the help.
I also have plans to try making lora on k2.2

**Comment by nikolaiusa** [comment]
![Снимок экрана (257)](https://github.com/seruva19/kubin/assets/134322831/c032658b-53b6-4860-a470-84d816176aea)
I trained lora but I don’t see it - do I need to move the files?
<img width="742" alt="2024-3-5 17-5-0" src="https://github.com/seruva19/kubin/assets/134322831/43452489-3b3c-4140-b590-9edaf625b5d3">

**Comment by nikolaiusa** [comment]
i found this in file - config.default.yaml

lora_path: networks/lora;train/lora
lora_prior_pattern: '*lora_prior*.bin;*lora_prior*.safetensors'
lora_decoder_pattern: '*lora_decoder*.bin;*lora_decoder*.safetensors'
autopair_lora_models: false

**Comment by nikolaiusa** [comment]
I'm a little confused, could you help? what format should the lora be in and where should it be located?

**Comment by nikolaiusa** [comment]
1 - I prepared a dataset- dataset.csv
2 - its my parametrs ( 50 -step for test) 
<img width="665" alt="2024-3-5 17-48-45" src="https://github.com/seruva19/kubin/assets/134322831/803a7f19-d635-4ae5-a0ec-a104230613b5">

3 - after train i see this 


lora prior training progress: 100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.45it/s, lr=1e-5, step_loss=0.0418]
lora prior training progress: 100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.46it/s, lr=1e-5, step_loss=0.0418]
training of LoRA prior model completed

4- and folders 
![Снимок экрана (259)](https://github.com/seruva19/kubin/assets/134322831/9c80b362-c1c1-4c0a-be5e-f5e1fbc44974)
![Снимок экрана (258)](https://github.com/seruva19/kubin/assets/134322831/360bb75a-79c1-47d1-a2b6-8264ba794d02)


5 -but i dont see lora here
<img width="599" alt="2024-3-5 17-55-0" src="https://github.com/seruva19/kubin/assets/134322831/a3d6c804-68d0-4106-a54b-59889f53a9c0">

**Comment by seruva19** [comment]
The default folders for LoRA files are "networks/lora" or "train/lora".
Prior LoRA weights must contain "lora_prior" in filename, and decoder weights must contain "lora_decoder" (it can be changed in 'kd-training' settings).
So, rename "model.safetensors" to something like "lora_prior_model.safetensors" and it should appear in the list.

**Comment by nikolaiusa** [comment]
> The default folders for LoRA files are "networks/lora" or "train/lora". Prior LoRA weights must contain "lora_prior" in filename, and decoder weights must contain "lora_decoder" (it can be changed in 'kd-training' settings). So, rename "model.safetensors" to something like "lora_prior_model.safetensors" and it should appear in the list.

thanks, it worked.

**Comment by nikolaiusa** [comment]
I wanted to ask a few questions, you can answer if it’s not difficult for you.

1 - Is it possible to regulate the power of lora?

2 - Is it possible to mix more than two images in mix mode?

3 - Kandinsky3 works without the Internet.
but My Kandinsky 2.2 requires an Internet connection to start generation. controlnet 2.2 also (the first time when kubin is turned on)

**Comment by seruva19** [comment]
> 1 - Is it possible to regulate the power of lora?

I use the diffusers implementation of Kandinsky 2.2 pipeline, and (to my knowledge) it does not expose parameters for adjusting LoRA scale. I think it's not that difficult to augment it into the pipeline, but I haven't been experimenting much in this direction.

> 2 - Is it possible to mix more than two images in mix mode?

Currently, not possible. Maybe later I'll implement it, would be pretty easy.

> 3 - Kandinsky3 works without the Internet.
> but My Kandinsky 2.2 requires an Internet connection to start generation. controlnet 2.2 also (the first time when kubin is turned on)

That's strange, I'll check it later.

**Comment by nikolaiusa** [comment]
mix for 4 images is my dream)

**Comment by seruva19** [comment]
> mix for 4 images is my dream)

OK, I'll put this feature into top of my TODO list :)
