### ISSUE TITLE
Add LLM-based prompt enhancer

### ISSUE THREAD

**Issue by adrianpuiu** [seruva19/kubin#176]
Hi  man, long time no see.

Any chance to get ollama  to enhance the prompts as an extension ?

**Comment by seruva19** [comment]
Oh, hello, nice to hear from you
Yes, I might consider that. I'm on vacation now :) but I will return soon.
To be honest, these days, I'm mostly interested in music AI, so I'm not paying much attention to image generation.

**Comment by Blucknote** [comment]
> I'm mostly interested in music AI

Do you have links to some good ones that can be inferenced locally?

**Comment by adrianpuiu** [comment]
the only insipiration for it 

> Oh, hello, nice to hear from you Yes, I might consider that. I'm on vacation now :) but I will return soon. To be honest, these days, I'm mostly interested in music AI, so I'm not paying much attention to image generation.

enjoy your holidays bro. Ai music seems crazy these days. when you get a chance if youre in the mood for a challenge take a look here as a source of inspiration :   https://github.com/if-ai/ComfyUI-IF_AI_tools/tree/main 

just the ollama ([ollama_api.py](https://github.com/if-ai/ComfyUI-IF_AI_tools/blob/main/ollama_api.py)) 
and the presets are [here](https://github.com/if-ai/ComfyUI-IF_AI_tools/tree/main/presets) 

let me know what you think

**Comment by adrianpuiu** [comment]
> > I'm mostly interested in music AI
> 
> Do you have links to some good ones that can be inferenced locally?

I left a reply to Сергий above. have a look

**Comment by seruva19** [comment]
> Do you have links to some good ones that can be inferenced locally?

In my opinion, the most capable options are:

Audiocraft library, which includes MusicGen/MAGNeT: [GitHub link](https://github.com/facebookresearch/audiocraft)
Riffusion: [GitHub link](https://github.com/riffusion/riffusion)
AudioLDM2: [GitHub link](https://github.com/haoheliu/AudioLDM2)

While they may not match the quality of Suno and Udio, they can be used locally and are at least capable of producing something that sounds like music. There are some others listed [here](https://github.com/Curated-Awesome-Lists/awesome-ai-music-generation), but they are inferior.

The turning point will be the anticipated release of the open-source version of Stable Audio 2. It's highly likely that it will be possible to train it with a consumer GPU (unlike MusicGen). In this case, the community will grow very quickly.

**Comment by adrianpuiu** [comment]
@seruva19 flare looks nice.
i'm doinga small app usign llm function calls app , a small py project , but i need to add quite a lot to it and no time because of work.
[lm3.txt](https://github.com/seruva19/kubin/files/15177157/lm3.txt)

i want to add speech 2 code, speech to speech, speech 2 code, speech 2 rag and  low latency so it can be interrupted at any given time . maybe a speech 2 rag , but ill need a scraper and beautiful soup its now what i need . and a funny personality given from the system prompt

**Comment by seruva19** [comment]
@adrianpuiu Nice! Text-to-speech is too developing so fast today, there are a lot of cool things happening. Unfortunately, there are only 24 hours in a day :(

**Comment by adrianpuiu** [comment]
@seruva19 unfortunaly yes, to little time. but we can learn to sleep faster as Arnold Schwarzenegger said :))

**Comment by adrianpuiu** [comment]
Thank you!

**Comment by seruva19** [comment]
@adrianpuiu No problem.
The functionality of this extension is pretty limited for now. If you will have any ideas on how to improve it, feel free to let me know. I am working on some LLM projects, on my main work as well, so any related experience is welcome :)
