### ISSUE TITLE
model 2.1 error in mixing mode..once again(( 

### ISSUE THREAD

**Issue by xyzzart** [seruva19/kubin#177]
yesterday all was fine///
![image](https://github.com/seruva19/kubin/assets/87940617/047d6e32-ef5a-4bd7-9564-ded48ca0dfcf)

**Comment by seruva19** [comment]
They update PyTorch from time to time (it's now 2.3.0 instead of 2.2.2), and FlashAttention library stops functioning because it was built for the older version of torch. It's inevitable and expected :)

I will recompile FlashAttention and update the colab shortly.

**Comment by xyzzart** [comment]
> They update PyTorch from time to time (it's now 2.3.0 instead of 2.2.2), and FlashAttention library stops functioning because it was built for the older version of torch. It's inevitable and expected :)
> 
> I will recompile FlashAttention and update the colab shortly.

thank you!

**Comment by xyzzart** [comment]
is it possible to use mixing mode with a new model?

**Comment by seruva19** [comment]
> is it possible to use mixing mode with a new model?

Yes (in theory), because for 3.1 they trained a [IP-Adapter](https://github.com/ai-forever/Kandinsky-3?tab=readme-ov-file#kandinsky-ip-adapter--kandinsky-controlnet) that allows image-to-image and mixing, but I haven't implemented it yet in Kubin (although eventually I will 🙂).

**Comment by seruva19** [comment]
Yes, 2.1 was really unique. 2.2 is also good, but it's more generic.
3.* models are actually not bad, but considering they are so resource-intensive, and now when we have PixArt Sigma, Stable Cascade, amazing finetunes for SDXL, and the upcoming leak of SD3 🤭, Kandinsky will have a hard time catching up.

**Comment by seruva19** [comment]
Should work properly now.
