### ISSUE TITLE
Cant run model 2.1 

### ISSUE THREAD

**Issue by xyzzart** [seruva19/kubin#180]
getting this error
![image](https://github.com/user-attachments/assets/c0cbc80f-e8e3-4ad9-909f-b9bd40c99502)

**Comment by seruva19** [comment]
Try `update.bat` script. It should reinstall all dependencies.

**Comment by seruva19** [comment]
Fixed the error.

**Comment by xyzzart** [comment]
colab wont work for me no more😭😪(( that sad

**Comment by seruva19** [comment]
Hmm, for real? What's the error?

**Comment by xyzzart** [comment]
calab said that the code in that one aint legit or smthng so you should to get a paid one...but after restart it worked fine. will see for how long..
