### ISSUE TITLE
Integrate Kandinsky diffusers pipeline

### ISSUE THREAD

**Issue by seruva19** [seruva19/kubin#44]
These wonderful folks have almost finished implementation of K2 in diffusers: https://www.github.com/huggingface/diffusers/pull/3308
That means I don't have to implement this on my own, which is great xD

To add it to app:
1. https://github.com/seruva19/kubin/blob/master/src/models/model_kd2.py has to be modified to support processing of input params and dispatch them to diffusers pipeline instead of "native" Kandinsky2_1 model
2. argument value "diffusers" for CLI argument "pipeline" wll be responsible for choosing diffusers implementation
3. if diffusers implementation turns out to be [more effective](https://github.com/seruva19/kubin/issues/30) than native (and I think it will), "--pipeline=diffusers" will be set as default

**Comment by seruva19** [comment]
They've done it.
https://huggingface.co/docs/diffusers/main/en/api/pipelines/kandinsky
Time to start integrating it into the app. I expect to benefit at least from [memory and speed optimizations](https://huggingface.co/docs/diffusers/main/en/optimization/fp16)

**Comment by user425846** [comment]
Does this bring kandinsky closer to being compatible with LoRAs? I tried
the diffusers lora dreambooth script but unfortunately it tells me that its
not available with multi language models. Any idea?

neutron_hare ***@***.***> schrieb am Mo. 29. Mai 2023 um
00:56:

**Comment by shutter-cat** [comment]
Let's hope new optimizations make it work on 8 gb cards

**Comment by seruva19** [comment]
@user425846 I don't know yet. I hope to adapt diffusers implementation of LoRA. But I haven't got much experience with ML.

**Comment by adrianpuiu** [comment]
> @user425846 I don't know yet. I hope to adapt diffusers implementation of LoRA. But I haven't got much experience with ML.

do these guys have the scripts ready for diffusers ?

**Comment by seruva19** [comment]
@adrianpuiu Yes, but only in preview version of diffusers. Follow the links I posted.

**Comment by adrianpuiu** [comment]
freaking hell they where fast. just finished reading their the t2i examples . I can't test it atm cause i have meetings with US about mid year priorities... freaking corporations ....but its good cause i work from home :))

**Comment by adrianpuiu** [comment]
well , clearly it's not implemented in the diffusers-0.16.1-py3-none-any.whl . do you have a dev wheel link ?

**Comment by adrianpuiu** [comment]
i got it going . thank you

**Comment by adrianpuiu** [comment]
> 
 my thinking is that having the diffuers added more devs will jump on the repo and help evolving it faster

**Comment by seruva19** [comment]
Either that, or someone will make better frontend for Kandinsky, so you guys won't be tied with my awkward GUI :)

**Comment by adrianpuiu** [comment]
lol , man, what are you talking about :)) the front look is freaking better then a1111 . :D   :D

**Comment by user425846** [comment]
I dont understand it too, the ui is perfectly fine haha

adrianpuiu ***@***.***> schrieb am Mo. 29. Mai 2023 um 15:38:

**Comment by seruva19** [comment]
I don't think so) But thanks anyway 😊
