### ISSUE TITLE
kubin.py: error: unrecognized arguments: --enable-flash-attention

### ISSUE THREAD

**Issue by tushengzhang** [seruva19/kubin#5]
(venv) PS L:\Kandinsky-2\kubin> py src/kubin.py --enable-flash-attention
usage: kubin.py [-h] [--device DEVICE] [--model-version MODEL_VERSION] [--use-flash-attention] [--cache-dir CACHE_DIR]
                [--output-dir OUTPUT_DIR] [--task-type TASK_TYPE] [--share SHARE] [--server-name SERVER_NAME]
                [--server-port SERVER_PORT] [--concurrency-count CONCURRENCY_COUNT] [--debug] [--locale LOCALE]
                [--model-config MODEL_CONFIG]
kubin.py: error: unrecognized arguments: --enable-flash-attention

**Comment by seruva19** [comment]
You should have "--use-flash-attention", not "--enable-flash-attention".
