### ISSUE TITLE
Incorrect URL when launching the local GUI in the console

### ISSUE THREAD

**Issue by NeuroLord** [seruva19/kubin#57]
When I run the interface activation command in powershell, I get the message "Running on local URL: http://0.0.0.0:7860", which is not active, but the wiki lists the correct page address (http://127.0.0.1:7860). I think this should be corrected so as not to mislead some people.

**Comment by seruva19** [comment]
You're right. I'll fix it.
I used "0.0.0.0", because I once had to debug some problems related with incorrect gradio tunneling when app was launched inside colab notebook, but now it's obsolete.

**Comment by seruva19** [comment]
fixed in [e4cb716](https://github.com/seruva19/kubin/commit/e4cb716242e014cab31fd502ed7193ae68a57990)
