### ISSUE TITLE
CUDA memory issue not reasonable pls advice

### ISSUE THREAD

**Issue by zappazack** [seruva19/kubin#65]
CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 6.00 GiB total capacity; 5.24 GiB already allocated; 0 bytes free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by seruva19** [comment]
You seem to have a 6GB card, and unfortunately, this model is not yet optimized to work properly on low-end GPUs. But the community is working on it, so presumably, in a month or so, we will have a solution.
You can try to lower the resolution of the output image.

**Comment by zappazack** [comment]
Thanks for the info. Currently I have a RTX 2060. Would a RTX 4070 work, 12GB VRAM?

**Comment by zappazack** [comment]
Just a short update: RTX 4070 works fine but without xformer option the generation of 4 standard batches 768x768 takes quite a long time. Waiting for this option...

**Comment by Blucknote** [comment]
> Thanks for the info. Currently I have a RTX 2060. Would a RTX 4070 work, 12GB VRAM?

I'm running on RTX 3060 with 12 Gb VRAM and able to generate up to 1368x768. Performance on 768x768 is 3 it/s which kinda fast on my taste
