### ISSUE TITLE
prompt + parameter metadata

### ISSUE THREAD

**Issue by nicolai256** [seruva19/kubin#72]
is there any way I can find the prompt and parameters again from images I generated?

**Comment by seruva19** [comment]
Currently params are not preserved when image is saved, but such feature will be  implemented in one of the future updates.

**Comment by nicolai256** [comment]
> Currently params are not preserved when image is saved, but such feature will be implemented in one of the future updates.

I added some pnginfo stuff for saving the parameters and prompt for t2i inside the image.

u can extract those easily with 
```
with Image.open(image_path) as image:
    metadata = image.info
    prompt = metadata.get("prompt")
    print(metadata)
    print(prompt)
```

didn't do i2i and others but yea
https://github.com/nicolai256/kubin

**Comment by seruva19** [comment]
I added saving metadata to code (062111b95c465e0efa4c75be844c7585a1466634 in dev branch).
Did not merge your fork directly, but used your code, thank you for it!

<details><summary>And btw saved metadata can be viewed in Image Browser.</summary>

![Screenshot_2](https://github.com/seruva19/kubin/assets/26826215/077d1cb9-57d5-4c35-bb35-327e4fc8e671)
</details>

**Comment by Acephalia** [comment]
@seruva19 didn't want to open a new thread as it was related, did we need to enable this feature anywhere? Mine doesn't seem to show any of the sorting options either. I have run the update.bat as well so I'm fairly sure everything is up to date.
