### ISSUE TITLE
Add batch processing for img2img

### ISSUE THREAD

**Issue by seruva19** [seruva19/kubin#75]

**Comment by makeoo1** [comment]
<3 <3 <3 <3 <3 <3 <3 <3

**Comment by makeoo1** [comment]
Hello!

i am not sure if i updated the webgui correclty. 

i ran git pull in /kubin folder
i ran the updated.bat file
i ran the install.bat file

everything seems fine during the process but when i open the webgui i don't see this feature in the img2img page.
i was expecting to find a path for a folder of images 

maybe i am missing something. 

Thank you for the help! :D 

![Screenshot 2023-05-19 141221](https://github.com/seruva19/kubin/assets/113861865/11dab9db-15a5-4504-9d0b-8e0374a1371e)

**Comment by Blucknote** [comment]
AFAIK this feature not implemented yet

**Comment by seruva19** [comment]
@makeoo1 Sorry for confusion. I am planning to add this feature, but it's not available yet. As soon as it will be implemented, I will write about it (in this issue).

**Comment by makeoo1** [comment]
no worries at all,

thank you guys!

**Comment by seruva19** [comment]
@makeoo1 There is now an option to do batch processing of images in i2i tab. 

<details><summary>screenshot</summary>

![image](https://github.com/seruva19/kubin/assets/26826215/ed9a9137-4b64-4ac2-b668-2f0e3cb53b55)

<details>

**Comment by makeoo1** [comment]
amazing! thx a lot!
