### ISSUE TITLE
Added RunPod template 

### ISSUE THREAD

**Issue by kodxana** [seruva19/kubin#89]
Link to template: https://runpod.io/gsc?template=hwwh1x6mhq&ref=vfker49t

All requirements preinstalled for all extensions.
Note for now model is not included (working to find correct model location)

![image](https://github.com/seruva19/kubin/assets/16674412/04c1a6c1-94ec-4085-9030-216e8dc4a78c)

**Comment by kodxana** [comment]
Password for jupiter notebook is always kubin :)

**Comment by seruva19** [comment]
That's great, thank you.

**Comment by kodxana** [comment]
exacly

**Comment by seruva19** [comment]
By default they are downloaded into "models/2_1/" in app's root.
There are also other folders (created by extensions). So usually full folder structure looks looks like that:

![image](https://github.com/seruva19/kubin/assets/26826215/09ee9b90-d818-4e8c-a301-f94c9e692837)

**Comment by adrianpuiu** [comment]
Sergey, did you tried visual code with the hugging face plugin and the new starcoder llm  instead of the Copilot ? if not you should give it a try... don't give it long prompts cause its messing up big time  ... if you wanna try a prompt will start with the #  and you can accept it hitting the tab key .... I tried it today and im quite impressed

**Comment by seruva19** [comment]
I've heard a lot about Star Coder, I will definitely try it.
I am using Amazon CodeWhisperer now and I like it. And ChatGPT too, of course :)

**Comment by adrianpuiu** [comment]
@kodxana  i asked the guys who made the ffusion_ai stable diffusion model if they would share their data set so we can train kandinsky ..  
```

FUSION AI Text Encoders:

    di.FFUSION.ai-tXe-FXAA: Trained on "121361" images. Enhance your model's quality and sharpness using the pre-trained Unet.

    di.FFUSION.ai-tXe-fX: Trained on "211924" images. Amplify your model's surrealism and effects.


```
link with beta released models [here](https://www.reddit.com/r/StableDiffusion/comments/13xx7yr/ffusion_ai_limited_public_beta_release_sd_21_512/)

**Comment by adrianpuiu** [comment]
> Sergey, did you tried visual code with the hugging face plugin and the new starcoder llm instead of the Copilot ? if not you should give it a try... don't give it long prompts cause its messing up big time ... if you wanna try a prompt will start with the # and you can accept it hitting the tab key .... I tried it today and im quite impressed

I can't use the AWS one  .... forgot my amazon password and frankly to lazy to recovery it :D

**Comment by kodxana** [comment]
> @kodxana i asked the guys who made the ffusion_ai stable diffusion model if they would share their data set so we can train kandinsky ..
> 
> ```
> 
> FUSION AI Text Encoders:
> 
>     di.FFUSION.ai-tXe-FXAA: Trained on "121361" images. Enhance your model's quality and sharpness using the pre-trained Unet.
> 
>     di.FFUSION.ai-tXe-fX: Trained on "211924" images. Amplify your model's surrealism and effects.
> ```
> 
> link with beta released models [here](https://www.reddit.com/r/StableDiffusion/comments/13xx7yr/ffusion_ai_limited_public_beta_release_sd_21_512/)

Sure reach me on RunPod discord you will find me as Madiator2011
