### ISSUE TITLE
img2img rendering random images

### ISSUE THREAD

**Issue by makeoo1** [seruva19/kubin#92]
Hi guys!

I am getting this wired renders only in img2img mode. everything else seems to work fine. 

before trying to render i ran git pull in the kubin folder, then ran update.bat 

I also did few test with all default settings but nothing changed

thx guys! :D

![Screenshot 2023-06-04 230936](https://github.com/seruva19/kubin/assets/113861865/09209c8b-651c-4b4b-ab14-598f0381bf7f)
![Screenshot 2023-06-04 231512](https://github.com/seruva19/kubin/assets/113861865/befb189b-ca99-42ee-945e-06912897829b)

other tabs seems to work fine
![image](https://github.com/seruva19/kubin/assets/113861865/ec11e8fb-6d25-4cc9-b68d-83a89940d21e)
![image](https://github.com/seruva19/kubin/assets/113861865/3e617044-c9f0-4c80-a104-c762f0f8bd6e)

**Comment by seruva19** [comment]
Hmm, that's strange. Does lowering image strength change anything?

**Comment by makeoo1** [comment]
no, i trired to tweak few settings here and there but nothing

**Comment by seruva19** [comment]
Understood, I'll try to figure it out.

**Comment by seruva19** [comment]
There was a bug, I fixed it.
You can update now, and it should not render completely random images )

![Screenshot_1](https://github.com/seruva19/kubin/assets/26826215/1fcdb060-58c6-4615-9129-463a2c182a2c)

**Comment by makeoo1** [comment]
yo thx! the single image process works fine now. 
I am having problems with the batch processing tho.
i tried first with the regular path of the folder which was in my HDD and was not working, then i also tried to copy the same folder in the kubin folder just for checking but still same error. 

thx for the help

![image](https://github.com/seruva19/kubin/assets/113861865/77e05529-1c8c-414a-92e1-e4754229ea54)

**Comment by seruva19** [comment]
That's... unexpected )
I recreated the same folders structure as in your screenshot and it works. 

![image](https://github.com/seruva19/kubin/assets/26826215/fa60a0cd-80df-4456-bceb-9d33857f2918)

Can you try some other folder? Or use relative path? For instance, you can refer to data inside "kubin" folder by relative path, like "images\BOOK OF HELL"

**Comment by makeoo1** [comment]
yo! so i made few tires and apparently it only works for me when the img folder is located in kubin folder like this

![image](https://github.com/seruva19/kubin/assets/113861865/24169e34-f312-49f4-8847-bd9a5014212f)
![image](https://github.com/seruva19/kubin/assets/113861865/1b0be61f-aef6-40e6-8586-c90cde749755)

**Comment by seruva19** [comment]
Right now I have no explanation for this (maybe some permission issue).
But at least batch processing works, that's good :)

**Comment by makeoo1** [comment]
hey no worries at all! thx for all the help and let me know if there is something i can do to help you :D
