### ISSUE TITLE
error when trying to generate in kandinsky 2.1 web ui

### ISSUE THREAD

**Issue by demirklvc** [seruva19/kubin#98]
Im getting this error when trying to generate: There is no current event loop in thread 'AnyIO worker thread'.

**Comment by seruva19** [comment]
In local mode or cloud service?
I once had such an error on Paperspace. But never locally. Can you give some context (stack trace)?

**Comment by demirklvc** [comment]
@seruva19 locally, running on windows on a 3090ti 24 gb ram. what more infos do you need? i cant really code, please explain to me what info is needed. appreciate your willigness to help, would love to use it.

**Comment by demirklvc** [comment]
if you interested i could give you access to the computer via rustdesk.

**Comment by demirklvc** [comment]
locally via gradio web ui server

**Comment by seruva19** [comment]
Can you copy the full text of error? I mean, there should be a lot of text before the line "There is no current event loop..." - that's what I need to understand the origin of the error.

**Comment by demirklvc** [comment]
i would if i could run kadinsky web ui. tried around 20 times to get ir running, when i use: python  src/kubin.py it gives me: module not found: real ersgan.

**Comment by seruva19** [comment]
Try to run the following:

`python src/kubin.py --disabled-extensions="kd-upscaler"`

Does it still give the error?

**Comment by demirklvc** [comment]
now i get following: ModuleNotFoundError: No module named 'clip_interrogator'

**Comment by user425846** [comment]
Why not use „sh start.sh“

keko ***@***.***> schrieb am Fr. 16. Juni 2023 um 21:22:

**Comment by seruva19** [comment]
I suspect some extensions were not installed correctly. Run:

`python src/kubin.py --safe-mode="use"`

This will launch app with disabled extensions. Will it work now?

**Comment by demirklvc** [comment]
thanks for the tips to both of yall. im now reinstalling and trying with that info. gonna update yall in couple minutes

**Comment by demirklvc** [comment]
reinstalled and when i try to generate im getting this: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by seruva19** [comment]
Check PyTorch version, what does it output?
```
python
import torch
torch.__version__
```

**Comment by demirklvc** [comment]
how do i do that? excuse me, i tried to input it into the windows terminal but im not getting info.

**Comment by demirklvc** [comment]
> pytorch version 3.10.6

@seruva19

**Comment by seruva19** [comment]
No, it's python version... OK, type this:
`python -c "import torch; print(torch.__version__)`

**Comment by demirklvc** [comment]
pytoch 2.0

**Comment by seruva19** [comment]
Only "2.0"?

**Comment by demirklvc** [comment]
2.0.1+cpu

**Comment by seruva19** [comment]
That means you have CPU version of PyTorch library installed. That happens sometimes, you just have to install it manually. Use this:

`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 `

Installation should take a while. After that, run `python -c "import torch; print(torch.__version__)"` again. If everything is OK, it should show `2.0.1+cu118`. Then try again to launch the webui app and generate something.

**Comment by demirklvc** [comment]
it is 2.0.1+cu118 now, but getting this: : Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
scanning system information

**Comment by seruva19** [comment]
Do you launch webui with `start.bat` or you do it manually?

**Comment by demirklvc** [comment]
start.bat

**Comment by demirklvc** [comment]
appreciate your willigness to help!

**Comment by demirklvc** [comment]
any idea what i can try now?

**Comment by seruva19** [comment]
Hmm, I have a suspicion that it does not actually install torch into webui environment...
Let's try the following: create a copy of start.bat file and change its contents to:

```
call venv\Scripts\activate.bat
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 
python src\kubin.py
```

(Or you can just  create a new .bat file inside 'kubin' folder)
Now try to launch this new file and let's see what happens :)

**Comment by demirklvc** [comment]
alright doing now!

**Comment by demirklvc** [comment]
> Hmm, I have a suspicion that it does not actually install torch into webui environment... Let's try the following: create a copy of start.bat file and change its contents to:
> 
> ```
> call venv\Scripts\activate.bat
> pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 
> python src\kubin.py
> ```
> 
> (Or you can just create a new .bat file inside 'kubin' folder) Now try to launch this new file and let's see what happens :)

done. same error message still :/

**Comment by demirklvc** [comment]
if it helps you could connect to my pc via rust desk

**Comment by seruva19** [comment]
Thos won't help, because I am actually out of ideas now :( 
Well, I have one more thing to check. Run:

`python src/kubin.py --device='cpu'`

Will the error change?

**Comment by demirklvc** [comment]
ModuleNotFoundError: No module named 'deepdiff' when i try to run manually.

**Comment by demirklvc** [comment]
doesnt work too...:(

**Comment by seruva19** [comment]
Launch `install.bat` and after installation ends run `python src/kubin.py --device='cpu'` again.

**Comment by demirklvc** [comment]
> Launch `install.bat` and after installation ends run `python src/kubin.py --device='cpu'` again.

still same error. here is the full terminal: 

To create a public link, set `share=True` in `launch()`.
scanning system information
task queued: text2img
clearing memory
loading default decoder model
loading default prior model
Traceback (most recent call last):
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\gradio\blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\RTX01\kubin\src\ui_blocks\t2i.py", line 105, in generate
    return generate_fn(params)
  File "C:\Users\RTX01\kubin\src\webui.py", line 32, in <lambda>
    generate_fn=lambda params: kubin.model.t2i(params),
  File "C:\Users\RTX01\kubin\src\models\model_kd2.py", line 104, in t2i
    params = self.prepare("text2img").seed(params)
  File "C:\Users\RTX01\kubin\src\models\model_kd2.py", line 39, in prepare
    self.kd2 = get_checkpoint(
  File "C:\Users\RTX01\kubin\src\engine\kandinsky.py", line 193, in get_checkpoint
    model = Kandinsky2_1(
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\kandinsky2\kandinsky2_1_model.py", line 57, in __init__
    self.prior.load_state_dict(torch.load(prior_path), strict=False)
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\RTX01\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\Users\RTX01\AppData\Local\Programs\Python\Python310\lib\pickle.py", line 1254, in load_binpersid
    self.append(self.persistent_load(pid))
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\RTX01\kubin\venv\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by seruva19** [comment]
Oh, well, OK.. I am sure there exists some simple answer to this. I have to leave now, but we will return to this problem later ;)

**Comment by demirklvc** [comment]
hey

**Comment by seruva19** [comment]
Hey, how it's going?

**Comment by demirklvc** [comment]
can we try further to set it up please? would love to use it! :)

**Comment by seruva19** [comment]
I would like to help, but I have no idea what's going wrong :(
Usually "clean" install (like described [here](https://github.com/seruva19/kubin/wiki/Docs#installation-and-usage-manual)) resolves 80% of errors, but looks like your case is different. 
Try to launch Powershell terminal and reproduce all the commands (from the link above) step by step.

**Comment by demirklvc** [comment]
> I would like to help, but I have no idea what's going wrong :( Usually "clean" install (like described [here](https://github.com/seruva19/kubin/wiki/Docs#installation-and-usage-manual)) resolves 80% of errors, but looks like your case is different. Try to launch Powershell terminal and reproduce all the commands (from the link above) step by step.

deleted everything, did a clean install via powershell and input everything step by step. still the same error, very frustrating.

**Comment by seruva19** [comment]
The same error is "Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False", right?

**Comment by demirklvc** [comment]
yes

**Comment by seruva19** [comment]
Can you open powershell terminal in 'kubin' folder and:
1. type "nvidia-smi" command, copy the output here
2. type " ./venv/Scripts/Activate.ps1", then "pip show torch" and also copy the result here

**Comment by demirklvc** [comment]
yes, doing now!

**Comment by demirklvc** [comment]
1:


+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.56       Driver Version: 527.56       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:04:00.0  On |                  N/A |
| 36%   20C    P8    30W / 336W |    799MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2652    C+G   ...bbwe\Microsoft.Photos.exe    N/A      |
|    0   N/A  N/A      4048    C+G   ...6.0.3.0\GoogleDriveFS.exe    N/A      |
|    0   N/A  N/A      4180    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      6124    C+G   ...\app-1.0.9013\Discord.exe    N/A      |
|    0   N/A  N/A      6604    C+G   ...zilla Firefox\firefox.exe    N/A      |
|    0   N/A  N/A      7264    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A      8704    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     10252    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     10732    C+G   ...8wekyb3d8bbwe\Cortana.exe    N/A      |
|    0   N/A  N/A     11912    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     12572    C+G   ...2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     13528    C+G   ...zilla Firefox\firefox.exe    N/A      |
|    0   N/A  N/A     13716    C+G   ...e\PhoneExperienceHost.exe    N/A      |
+-----------------------------------------------------------------------------+

**Comment by demirklvc** [comment]
2:

Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\rtx01\kubin\venv\lib\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: clip, clip-interrogator, fairscale, kandinsky2, open-clip-torch, pytorch-lightning, RealESRGAN, shap-e, timm, torchmetrics, torchvision

**Comment by seruva19** [comment]
OK. Now, for completeness of information, I need also the output of this command (the same way, type it in terminal):

`git log --pretty=format:'%h' -n 1`

**Comment by demirklvc** [comment]
4b7a962

**Comment by seruva19** [comment]
Nice, now let's try this (step by step):

```
./venv/Scripts/Activate.ps1
python -c "import torch; print(torch.__version__)"
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
python -c "import torch; print(torch.__version__)"
py src/kubin.py
```

The questions are:
1. What are the outputs of line 2 and line 4 (versions of pytorch)?
2. Does the final output (after webui starts) still contains the same error as before?

**Comment by demirklvc** [comment]
doing now, reporting asap back

**Comment by demirklvc** [comment]
(venv) PS C:\Users\RTX01\kubin> python -c "import torch; print(torch.__version__)"
2.0.1+cpu
(venv) PS C:\Users\RTX01\kubin> python -c "import torch; print(torch.__version__)"
2.0.1+cpu

result: RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by seruva19** [comment]
So the error is: somehow the CUDA (GPU) version of pytorch is not installed despite direct instructions. And then it tries to run app using CPU instead of GPU and expectedly fails :)
Well, this is actually something that we can work with. Let's try these commands now (notice the third and last line are different now):

```
./venv/Scripts/Activate.ps1
python -c "import torch; print(torch.__version__)"
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
python -c "import torch; print(torch.__version__)"
python src/kubin.py
```

What are the versions output and final result now?

**Comment by demirklvc** [comment]
okay doing now :) thanks again, love your support

**Comment by demirklvc** [comment]
IT WORKS!

**Comment by demirklvc** [comment]
thanks alot!!! <3

**Comment by demirklvc** [comment]
anyway to improve speed? for now, it takes around 20 seconds for one image (768x768)

**Comment by seruva19** [comment]
Wait, really works? I had a lot of other ideas to test 😄

**Comment by demirklvc** [comment]
yes :)

**Comment by seruva19** [comment]
Concerning speed: you can try diffusers version, but I am not sure if it will be faster. To enable diffusers, go to 'Settings' - ''General' and select 'diffusers'. Then press 'Apply changes' and 'Save changes'. 
There probably will be some speed optimizations in future, I am only starting to understand how all this stuff works ;)
